package software.amazon.applicationinsights.application;

public enum Step {
    APP_CREATION,
    APP_UPDATE,
    TAG_CREATION,
    TAG_DELETION,
    COMPONENT_CREATION,
    COMPONENT_DELETION,
    LOG_PATTERN_CREATION,
    LOG_PATTERN_DELETION,
    LOG_PATTERN_UPDATE,
    COMPONENT_CONFIGURATION,
    DEFAULT_COMPONENT_CONFIGURATION,
    DISABLE_COMPONENT_CONFIGURATION;
}
